services:
  - type: web
    name: lemadh-thesis-ai-detector
    env: python
    buildCommand: ./render-build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
